services:
  lumen:
    build: .
    ports:
      - "8501:8501"
    container_name: lumen-app
    restart: unless-stopped
    volumes:
      - .:/app
    environment:
      - STREAMLIT_SERVER_RUN_ON_SAVE=true
      - STREAMLIT_SERVER_FILE_WATCHER_TYPE=poll
